export const INITIAL_PROBLEMS = [
  {
    id: "p1",
    title: "22 Crore Indians Still Have No Access to Clean Drinking Water",
    category: "Rural Development", // Wait, this requires SectorType. Need to check type. I'll pass as string then cast.
    description: "Millions of rural households rely on contaminated groundwater. Prolonged exposure causes severe health issues and high early mortality rate.",
    source: "NFHS-5",
    affected: "22 Cr people",
    currentFundingLCr: 0.85,
    neededFundingLCr: 1.5,
    votes: 184532,
    trending: true,
    impactScore: 9.4,
    state: "Maharashtra"
  },
  {
    id: "p2",
    title: "Government Schools in Bihar Have 40% Vacant Teacher Positions",
    category: "Education",
    description: "Severe lack of functioning educators in rural areas leaves students without basic literacy and numeracy skills, driving massive inequality.",
    source: "ASER 2025",
    affected: "1.2 Cr students",
    currentFundingLCr: 0.12,
    neededFundingLCr: 0.45,
    votes: 142384,
    governmentResponded: true,
    impactScore: 8.8,
    state: "Bihar"
  },
  {
    id: "p3",
    title: "Farmer Suicide Rate Up 12% — Crop Insurance Not Reaching Rural Areas",
    category: "Agriculture & Allied Activities",
    description: "Extreme weather has destroyed crops, but complex bureaucratic processes mean insurance payouts never reach the most vulnerable farmers.",
    source: "NCRB Data",
    affected: "14 Cr farmers",
    currentFundingLCr: 1.2,
    neededFundingLCr: 2.5,
    votes: 215442,
    trending: true,
    impactScore: 9.7,
    state: "Maharashtra"
  },
  {
    id: "p4",
    title: "Air Pollution in Delhi 15x Above Safe Limit — Needs Urgent Funding",
    category: "Science, Technology & Environment",
    description: "Toxic smog blankets the capital for 4 months a year, causing permanent lung damage to children and elderly residents.",
    source: "WHO Air Quality",
    affected: "3 Cr people",
    currentFundingLCr: 0.05,
    neededFundingLCr: 0.3,
    votes: 198221,
    impactScore: 9.1,
    state: "Delhi (NCT)"
  },
  {
    id: "p5",
    title: "1 in 4 Government Hospitals Has No Full-Time Doctor",
    category: "Health & Family Welfare",
    description: "Rural Primary Health Centers severely lack staff. Preventable diseases turn fatal because residents have to travel 50+ km for care.",
    source: "Rural Health Stats",
    affected: "45 Cr people",
    currentFundingLCr: 2.1,
    neededFundingLCr: 4.8,
    votes: 165330,
    governmentResponded: true,
    impactScore: 9.5,
    state: "Uttar Pradesh"
  },
  {
    id: "p6",
    title: "60% of Rural Roads Destroyed in 2024 Flood Season — Not Rebuilt Yet",
    category: "Infrastructure & Transport",
    description: "Vital economic lifelines connecting villages to market towns remain washed away, devastating local commerce.",
    source: "Ministry of Road Transport",
    affected: "8 Cr people",
    currentFundingLCr: 3.4,
    neededFundingLCr: 5.2,
    votes: 112450,
    impactScore: 8.4,
    state: "Assam"
  },
  {
    id: "p7",
    title: "Severe Lack of Women Safety Infrastructure in Tier 2 Cities",
    category: "Social Welfare (Women, Child, SC/ST)",
    description: "Lack of street lighting, CCTV coverage, and safe public transit makes evening commutes highly dangerous for women.",
    source: "Women & Child Dev",
    affected: "18 Cr women",
    currentFundingLCr: 0.4,
    neededFundingLCr: 1.2,
    votes: 189200,
    impactScore: 9.0,
    state: "Haryana"
  },
  {
    id: "p8",
    title: "Youth Unemployment Crisis: 42% of Graduates Under 25 Have No Jobs",
    category: "Education",
    description: "Skill mismatch and lack of industrial training centers leave millions of educated youth completely unemployable.",
    source: "CMIE Report",
    affected: "5 Cr youth",
    currentFundingLCr: 0.9,
    neededFundingLCr: 2.0,
    votes: 245000,
    trending: true,
    impactScore: 9.8,
    state: "Kerala"
  },
  {
    id: "p9",
    title: "No Specialized Healthcare Access for 12 Crore Senior Citizens",
    category: "Health & Family Welfare",
    description: "Geriatric wards are virtually non-existent in state hospitals, leaving the elderly reliant on unaffordable private care.",
    source: "NHM Survey",
    affected: "12 Cr seniors",
    currentFundingLCr: 0.2,
    neededFundingLCr: 0.8,
    votes: 95400,
    impactScore: 8.2,
    state: "Tamil Nadu"
  },
  {
    id: "p10",
    title: "Digital Connectivity Blackouts in 40,000 Remote Tribal Villages",
    category: "Science, Technology & Environment",
    description: "Without basic 4G internet, students cannot access digital learning and farmers cannot access critical weather or market data.",
    source: "TRAI Audit",
    affected: "2.5 Cr people",
    currentFundingLCr: 0.15,
    neededFundingLCr: 0.5,
    votes: 82100,
    impactScore: 7.9,
    state: "Chhattisgarh"
  },
  {
    id: "p11",
    title: "35% of Children Under 5 Suffering from Severe Malnutrition",
    category: "Social Welfare (Women, Child, SC/ST)",
    description: "Anganwadi centers are underfunded, leading to stunted growth and permanent cognitive damage in millions of children.",
    source: "Global Hunger Index",
    affected: "4 Cr children",
    currentFundingLCr: 1.1,
    neededFundingLCr: 2.4,
    votes: 178000,
    impactScore: 9.6,
    state: "Madhya Pradesh"
  },
  {
    id: "p12",
    title: "Massive Commercial Vehicle Pollution: Zero EV Truck Charging Networks",
    category: "Energy & Power",
    description: "Diesel freight transport contributes heavily to national emissions, but heavy-duty electric vehicle infrastructure is 0%.",
    source: "NITI Aayog",
    affected: "National",
    currentFundingLCr: 0.3,
    neededFundingLCr: 1.5,
    votes: 64200,
    isNew: true,
    impactScore: 7.5,
    state: "Gujarat"
  },
  {
    id: "p13",
    title: "Tribal Area Education Access: Nearest Schools are 15km Away",
    category: "Education",
    description: "Without government-funded transport or local hostels, indigenous children are forced to drop out after primary school.",
    source: "Ministry of Tribal Affairs",
    affected: "90 Lakh children",
    currentFundingLCr: 0.25,
    neededFundingLCr: 0.9,
    votes: 104500,
    impactScore: 8.7,
    state: "Jharkhand"
  },
  {
    id: "p14",
    title: "Mental Health Epidemic: Only 1 Counselor per 2 Lakh Citizens",
    category: "Health & Family Welfare",
    description: "Post-COVID trauma and economic stress are surging, but public mental health infrastructure is absolutely non-existent.",
    source: "Indian Psych Society",
    affected: "National",
    currentFundingLCr: 0.08,
    neededFundingLCr: 0.6,
    votes: 154200,
    isNew: true,
    impactScore: 8.9,
    state: "Karnataka"
  },
  {
    id: "p15",
    title: "Coastal Fishermen Livelihoods Devastated by Extreme Weather",
    category: "Agriculture & Allied Activities",
    description: "Cyclones are destroying boats and nets, but emergency relief funds and modern weather-warning systems are dangerously underfunded.",
    source: "Ministry of Earth Sciences",
    affected: "1.5 Cr people",
    currentFundingLCr: 0.1,
    neededFundingLCr: 0.4,
    votes: 72000,
    impactScore: 8.0,
    state: "Odisha"
  }
];
